require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'
    - 'db/migrate/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/migrate/*'
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
    - 'db/migrate/*'
Rails/Date:
  # TODO: figure out how to configure ActiveSupport::TimeZone without rails
  Enabled: false
Rails/TimeZone:
  # TODO: figure out how to configure ActiveSupport::TimeZone without rails
  Enabled: false
Rails/HttpPositionalArguments:
  Exclude:
    - 'spec/controllers/**/*'
RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'
RSpec/MultipleExpectations:
  Max: 5
Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/*'
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
